### PR TITLE
deb | flo: Remove liboemcrypto.so lib and fix Netflix

### PR DESCRIPTION
**Pull request by semdoc**
All credits goes to @MajorTom_ & @Bonestack from XDA for solution

Change-Id: Ib594e9452252aa667bcff6a84ff4b32ebe06b89e

### CODE REVIEW

**Comment by dhacker29** [comment]
Why would level 1 not with in cm when it works in stock? Unless you have messed up the kernel side crypto?

**Comment by nardholio** [comment]
dhacker, I'm making inquiries, the explanation that was given to me was
bootloader unlock. Somebody's going to have to relock their bootloader to
test it.

**Comment by nardholio** [comment]
Netflix works for me as of a few days ago. Not sure what may have changed
on that front as well.

**Comment by nardholio** [comment]
Not merging this yet, netflix works for me

**Comment by chrmhoffmann** [comment]
Apparently netflix and livedisplay conflicts. Disable livedisplay and netflix works.

**Pull request closed without merging**
