### PR TITLE
deb: Update blobs to 5.1.0 release (LMY47O)

### PR DESCRIPTION
**Pull request by semdoc**
Change-Id: Iac45edaa8ec46de634de551e421df14261185ffc

### CODE REVIEW

**Comment by semdoc** [comment]
Used libacdbdata.so lib from flo (LMY47O)

**Comment by intervigilium** [comment]
You changed the file modes on every single file. That would make it kind of tricky to figure out what actually changed.

**Comment by semdoc** [comment]
@intervigilium, Now It should be fine. Blobs were extracted with extract-files.sh script properly.

**Comment by nardholio** [comment]
Does the deb file still not boot properly?

**Comment by semdoc** [comment]
@nardholio, You are right. The reason was that freaking libacdbdata.so lib. And @intervigilium fixed with reverting to L preview version. Now my deb is fine again. Thank you Ethan :)

**Pull request closed without merging**
