### PR TITLE
Add blobs for Deb (Nexus 7 v2 LTE)

### PR DESCRIPTION
**Pull request by romracer**
Pulled from my device running the latest Google release for the 2013 Nexus 7 LTE (JLS36C).  Associated Gerrit change: http://review.cyanogenmod.org/#/c/51033/

### CODE REVIEW

**Comment by Goldflame09** [comment]
Can this be merged please?

Everything is working as it should

**Comment by Danesh** [comment]
No need for apns-conf.xml, cm has a global one.

**Comment by romracer** [comment]
Danesh, that is true.  To be fair though, I actually overwrite the included APN list with the CM list by including GSM bits.  I can update the pull request if desired.  I was trying to hold off on too many changes at first just so we could get an official build going then begin some cleanup of deb (and merging of deb/flo with Kelvie Wong and others).

**Comment by ciwrl** [comment]
Should this be updated to JLS36I props? (not sure there is much of a change)

**Comment by Goldflame09** [comment]
Still good. Can this be merged please?

**Pull request merged**
