### PR TITLE
flo, deb: hax sensor blob

### PR DESCRIPTION
**Pull request by fourkbomb**
Change-Id: Idd222d8d42e6625edb071b6cb5c70b752783eb41

### CODE REVIEW

**Comment by nardholio** [comment]
What does the patch do? Also what is the feasibility of open sourcing
the sensors blob instead of hacking it?

**Comment by fourkbomb** [comment]
it's from @Ziyann. He said he'd explain what exactly it does tomorrow.

I would like to get flo running with an OSS hal, but not sure if there's a better place to start than just stracing the sensor HAL

**Comment by Ziyann** [comment]
Here's a decompile of the problematic function: http://pastebin.com/9yetKCns. The issue is at lines 169 and 170.
I shimmed the poll() function for testing; notice the difference between clang/gcc built libc: http://pastebin.com/Z3Skfqyt. Somehow, the upper 16 bits of pollfd+3 (immediately after the end of the pollfd struct, v66) always get set to 0xFFFF with clang; with gcc, it's always 0x0, hence always passing that strange if condition. I don't really know what it's checking (it could be bogus...), but as far as I see, simply omitting it (and not caring about 0xFFFF there) is fine. I might investigate it again tonight to see if there's a better solution, but for now, I use the above hex edited blob: replaced a BEQ instruction with B (unconditional branch instead of branch if zero).

**Comment by nardholio** [comment]
Might be better to switch off of clang

**Comment by Ziyann** [comment]
It felt like a good idea to try hacking the blob instead, as bionic master branch won't build with gcc anymore. If anyone has an idea about that strange if condition, let me know what's up; as far as I see, it could even be an uninitialized variable or something similar.

**Pull request merged**
